<!--#include file="/resources/popup/header.php" -->
<p><strong>Uncensored/With Derpy Hooves &quot;The Last Roundup&quot; 1080p Episode </strong></p>
<p>iTunes released the original edition of &quot;The Last Roundup&quot; in 720p. Shortly after, it was removed from the store. After a month the episode returned with edits done to the pony known as Derpy. Rainbow Dash no longer referred to her as &quot;Derpy&quot; and Derpy's eyes were no longer crossed. Essentially, Derpy was removed from the episode.</p>
<p>When iTunes released the 1080p editions of the episodes, the The Last Roundup episode was released as the later edition, with Derpy removed. There was no 1080p release of the original video.</p>
<p>We found this very offensive, and are strongly against censorship. However, the only edition available is the one with Derpy effectively removed. We can not release a 1080p version of an episode that does not exist ... or can we?</p>
<p>WE CAN!</p>
<p>In between seasons 2 and 3, we worked hard to re-build the edited sections of this episode and restore the original video. We did not simply up-scale the 720p content, but restored every <a href="http://en.wikipedia.org/wiki/Film_frame">frame</a> by hand to re-include our beloved Derpy! We literally extracted the individual frames and hand edited them individually to restore this episode to it's original masterpiece edition!</p>
<p>The process was long, and many ponies worked hard on this very arduous and complex process, but we are finally proud to announce that we have a full 1080p edition of the original &quot;The Last Roundup&quot; episode, fully restored and re-mastered! This episode is full of Derpy and awesomeness!</p>
<p>P.S.: There are no subtitles included in this edition. If you would like subtitles, please download them from <a href="https://docs.google.com/uc?id=0B8nfVjxf8zhJMTdhNjZmMDktNjhhZi00MmI1LThmYTEtNThmMDY3NjkzNGVk&amp;hl=en_US">HERE</a> (Thanks to grayjeager)</p>
</div>